services:
  youtube-trends:
    build: .
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - JUSTJACKPOT_API_URL=${JUSTJACKPOT_API_URL}
    volumes:
      - .:/app
    command: --region IT --max-results 10 