name: YouTube Scraper Runner

on:
  schedule:
    - cron: '*/30 * * * *'  # ogni 30 minuti
  workflow_dispatch:  # lancio manuale

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Create firestore-access.json file
        run: printf '%s' '${{ vars.FIREBASE_JSON }}' > firestore-access.json

      - name: Check authentication method
        run: |
          if [ -n "${{ secrets.YOUTUBE_USERNAME }}" ] && [ -n "${{ secrets.YOUTUBE_PASSWORD }}" ]; then
            echo "✅ YouTube credentials found - will use Selenium for fresh cookie generation"
          else
            echo "❌ No YouTube credentials available - scraper will run without authentication"
            echo "💡 Add YOUTUBE_USERNAME and YOUTUBE_PASSWORD secrets for automated authentication"
          fi
          echo "🚫 Static YOUTUBE_COOKIES are ignored - only fresh cookies are used"

      - name: Create data directory
        run: mkdir -p data

      - name: Build and run Docker container
        run: |
          docker build -t youtube-scraper .
          # Mount firestore credentials only
          DOCKER_MOUNTS="-v $(pwd)/firestore-access.json:/app/firestore-access.json"
          
          # Set up environment variables for automated cookie generation only
          DOCKER_ENV=""
          if [ -n "${{ secrets.YOUTUBE_USERNAME }}" ] && [ -n "${{ secrets.YOUTUBE_PASSWORD }}" ]; then
            DOCKER_ENV="-e YOUTUBE_USERNAME='${{ secrets.YOUTUBE_USERNAME }}' -e YOUTUBE_PASSWORD='${{ secrets.YOUTUBE_PASSWORD }}'"
            echo "🚀 Using Selenium automated fresh cookie generation"
          else
            echo "⚠️ No credentials available - running without authentication"
          fi
          
          docker run $DOCKER_MOUNTS $DOCKER_ENV youtube-scraper
